### ISSUE TITLE
Debug builds with intrinsics broken w/ gcc 5.1

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1286]
```
$ make -s distclean; ./configure
[...]
Target CPU .................................. x86_64 AVX2, 64-bit LE
AES-NI support .............................. depends on OpenSSL
Target OS ................................... linux-gnu
Cross compiling ............................. no
Legacy arch header .......................... x86-64.h
[...]
Development options (these may hurt performance when enabled):
Memdbg memory debugging settings ............ disabled
AddressSanitizer ("ASan") ................... disabled

Install missing libraries to get any needed features that were omitted.

Configure finished.  Now 'make clean && make -s' to compile.
```

```
$ make -s clean
$ make -s debug
```
results in tons of error messages:
```
$ make -s debug
In file included from /usr/lib/gcc/x86_64-redhat-linux/5.1.1/include/immintrin.h:41:0,
                 from pseudo_intrinsics.h:174,
                 from rawSHA256_ng_fmt_plug.c:40:
rawSHA256_ng_fmt_plug.c: In function ‘crypt_all._omp_fn.0’:
/usr/lib/gcc/x86_64-redhat-linux/5.1.1/include/avxintrin.h:888:1: error: inlining failed in call to always_inline ‘_mm256_store_si256’: optimization level attribute mismatch
 _mm256_store_si256 (__m256i *__P, __m256i __A)
 ^
In file included from rawSHA256_ng_fmt_plug.c:40:0:
pseudo_intrinsics.h:211:33: error: called from here
 #define vstore(x, y)            _mm256_store_si256((void*)(x), y)
                                 ^
rawSHA256_ng_fmt_plug.c:354:9: note: in expansion of macro ‘vstore’
         vstore((vtype*) &crypt_key[7][index], h);
         ^
In file included from /usr/lib/gcc/x86_64-redhat-linux/5.1.1/include/immintrin.h:41:0,
                 from pseudo_intrinsics.h:174,
                 from rawSHA256_ng_fmt_plug.c:40:
/usr/lib/gcc/x86_64-redhat-linux/5.1.1/include/avxintrin.h:888:1: error: inlining failed in call to always_inline ‘_mm256_store_si256’: optimization level attribute mismatch
 _mm256_store_si256 (__m256i *__P, __m256i __A)
 ^
In file included from rawSHA256_ng_fmt_plug.c:40:0:
pseudo_intrinsics.h:211:33: error: called from here
 #define vstore(x, y)            _mm256_store_si256((void*)(x), y)
                                 ^
[...]
In file included from rawSHA256_ng_fmt_plug.c:40:0:
pseudo_intrinsics.h:189:33: error: called from here
 #define vload(x)                _mm256_load_si256((void*)(x))
                                 ^
rawSHA256_ng_fmt_plug.c:254:17: note: in expansion of macro ‘vload’
          w[i] = vload((vtype*) __w[i]);
                 ^
Makefile:1328: recipe for target 'rawSHA256_ng_fmt_plug.o' failed
make[2]: *** [rawSHA256_ng_fmt_plug.o] Error 1
Makefile:182: recipe for target 'default' failed
make[1]: *** [default] Error 2
Makefile:201: recipe for target 'debug' failed
make: *** [debug] Error 2
```

**Comment by magnumripper** [comment]
What version gcc is that? Doesn't happen on well, with gcc 4.9.2. Not a single warning.

**Comment by magnumripper** [comment]
OK I see it's gcc 5.1.1. I would regard it a compiler bug. We do nothing wrong.

**Comment by frank-dittrich** [comment]
That's the gcc 5.1.1 from Fedora 22 Beta.
I can't reproduce with 32bit AVX2 on Fedora 21 and not with 64bit AVX (not AVX2) on Fedora 20.
So may be I have to report a Fedora bug.

**Comment by magnumripper** [comment]
Are you saying you don't see it with gcc 5.1.1 on F20 and F21?

**Comment by frank-dittrich** [comment]
No. Fedora 20 still uses gcc 4.8.3, and Fedora 21 uses gcc 4.9.2
Will try clang on Fedora 22 next.

**Comment by magnumripper** [comment]
You are wasting your time. See if you can reproduce with gcc 5.0. Bug is likely gcc, not Fedora.

**Comment by magnumripper** [comment]
I see the same with gcc 5.1.0 (OSX, Homebrew)

**Comment by frank-dittrich** [comment]
Actually, I don't care much about what compiler gets me a working debug build, I' just take any one that works, because I try to figure out the cause of another bug right now.

**Comment by magnumripper** [comment]
A bug that's only seen in F22 beta? I would stay out of it. We have enough issues without investigating external beta problems.

**Comment by magnumripper** [comment]
Considering the output I bet you'll get the problem even with `-mo-avx2`.

**Comment by magnumripper** [comment]
Editing Makefile and changing `-Og` to `-O1` does not help. Changing it to `-O2` works fine but defeats most of the purpose with the debug target.

**Comment by magnumripper** [comment]
We can't work around this: Even if we define away all use of `inline` in our tree, there are still always_inline instances in the compiler's own intrinsics headers!

I also can't find this bug in the gcc bug tracker. Which is kind of strange! Is this happening due to some combination of other flags? We should try to make a simple test case.

**Comment by magnumripper** [comment]
OK this is odd. This should trigger the same problem:
```
#include <stdio.h>
#include <immintrin.h>

int main(int argc, char **argv)
{
	__m128i a;
	unsigned long int *b = (unsigned long int*)&a;

	a = _mm_set1_epi32(0);
	a = _mm_insert_epi32(a, 0x12345678, 3);

	printf("%016lx\n", b[1]);
}
```

I compile like this (the `-Wa,-q` is OSX-specific):
```
gcc -c -g -O2 test.c -o test.o -fomit-frame-pointer --param allow-store-data-races=0 -fopenmp -pthread -mavx -Wa,-q -std=gnu89 -Og
```

...but I can't reproduce the problem.

**Comment by magnumripper** [comment]
OK, this problem is not what I thought. Only two files are affected: rawSHA256_ng_fmt_plug.c and rawSHA512_ng_fmt_plug.c
