### ISSUE TITLE
bugs while installing jumbo john

### ISSUE THREAD

**Issue by Setplus01** [magnumripper/JohnTheRipper#2931]
Well, I have some problems with installing JtR. Here my commands (Ubuntu 16.04 LTS):

`sudo apt-get install build-essential libssl-dev`
`sudo apt-get install yasm libgmp-dev libpcap-dev libnss3-dev libkrb5-dev pkg-config libbz2-dev zlib1g-dev`
`sudo apt-get install libopenmpi-dev openmpi-bin`
`  sudo apt-get install subversion cmake bison flex`
`  mkdir ~/src && cd ~/src`
`  svn checkout https://github.com/teeshop/rexgen.git rexgen`
`  cd rexgen/trunk/src/`
`  mkdir build && cd build `
`  cmake ..`
`  make && sudo make install`
`cd ~/src`
`git clone git://github.com/magnumripper/JohnTheRipper -b bleeding-jumbo john`
`cd ~/src/john/src`
`./configure --enable-mpi && make -s clean && make -sj8`

After that I have following errors:

```
misc.c: In function ‘real_error_msg’:
misc.c:63:2: warning: ‘args’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  vfprintf(stderr, format, args);
  ^
ar: creating aes.a
ar: creating secp256k1.a
encfs_fmt_plug.o: In function `init':
/home/setplus/src/john/src/encfs_fmt_plug.c:80: undefined reference to `OPENSSL_init_ssl'
/home/setplus/src/john/src/encfs_fmt_plug.c:81: undefined reference to `OPENSSL_init_ssl'
/home/setplus/src/john/src/encfs_fmt_plug.c:82: undefined reference to `OPENSSL_init_crypto'
/home/setplus/src/john/src/encfs_fmt_plug.c:87: undefined reference to `OpenSSL_version_num'
gpg_common_plug.o: In function `gpg_common_check':
/home/setplus/src/john/src/gpg_common_plug.c:1587: undefined reference to `DSA_set0_pqg'
/home/setplus/src/john/src/gpg_common_plug.c:1588: undefined reference to `DSA_set0_key'
gpg_common_plug.o: In function `check_dsa_secret_key':
/home/setplus/src/john/src/gpg_common_plug.c:1081: undefined reference to `DSA_get0_pqg'
/home/setplus/src/john/src/gpg_common_plug.c:1082: undefined reference to `DSA_get0_key'
listconf.o: In function `listconf_list_build_info':
/home/setplus/src/john/src/listconf.c:207: undefined reference to `OpenSSL_version_num'
/home/setplus/src/john/src/listconf.c:208: undefined reference to `OpenSSL_version_num'
/home/setplus/src/john/src/listconf.c:213: undefined reference to `OpenSSL_version'
/home/setplus/src/john/src/listconf.c:214: undefined reference to `OpenSSL_version'
collect2: error: ld returned 1 exit status
Makefile:1506: recipe for target '../run/john' failed
make[1]: *** [../run/john] Error 1
Makefile:175: recipe for target 'default' failed
make: *** [default] Error 2
```

I can't understand what to do. Help me please.

**Comment by jfoug** [comment]
https://www.openssl.org/docs/man1.1.0/ssl/OpenSSL_add_ssl_algorithms.html

```
HISTORY

The SSL_library_init() and OpenSSL_add_ssl_algorithms() functions were deprecated in OpenSSL 1.1.0 by OPENSSL_init_ssl().
```

I wonder if your OpenSSL headers do not match your OpenSSL libraries ?

Try:

sudo apt-get install libssl

**Comment by jfoug** [comment]
NOTE, I believe we still have problems supporting oSSL v1.1 in general.  the problem is some of the versioning items were depreciated in 1.1 and REMOVED.  The listconf.c file will not build as it is in v1.1

**Comment by Setplus01** [comment]
@jfoug , well, i try `dpkg --add-architecture i386
apt-get update
apt-get install libssl-dev:i386` and get the same errors...(

**Comment by jfoug** [comment]
Have you tried to update the libssl like I asked?    The build sounds like your headers and libs are NOT in sync.

**Comment by Setplus01** [comment]
@jfoug , your command `sudo apt-get install libssl` don't work, when i am trying to use it in terminal.. So i change it to commands from my last answer

**Comment by kholia** [comment]
@Setplus01 Which Linux distribution are you using? I don't think that you are using `Ubuntu 16.04 LTS` or `Ubuntu 17.10`. I suspect that you are using `Kali Linux` or something based on Debian `sid`.

https://launchpad.net/ubuntu/artful/+package/libssl-dev still uses OpenSSL 1.0.2 series which is known to work.

**Comment by Setplus01** [comment]
@kholia , no-no, i use `Ubuntu 16.04 TLS` and that is crazy for me too ...

**Comment by kholia** [comment]
I believe that these compilation errors cannot be triggered on a regular `Ubuntu 16.04 LTS` installation. Your installation of Ubuntu is likely broken. Perhaps reinstall, and retry?

I think it is better to discuss this issue on http://www.openwall.com/lists/john-users/.

**Comment by Setplus01** [comment]
@kholia , ok, thanks

**Comment by kholia** [comment]
For reference purposes,

+ Current JtR Jumbo builds fine on `Kali 2017.3`.

+ https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes is relevant to this topic.
