### ISSUE TITLE
Problem with recent raw-md4-opencl merge

### ISSUE THREAD

**Issue by magnumripper** [magnumripper/JohnTheRipper#1442]
Introduced by 9c9b57ea5

This is from CircleCI bot Win64 build (btw it's not even an OpenCL build):
```
build_table.c: In function 'alarm_handler':
build_table.c:70:13: error: 'SIGALRM' undeclared (first use in this function)
  if (sig == SIGALRM) {
             ^
build_table.c:70:13: note: each undeclared identifier is reported only once for each function it appears in
build_table.c: In function 'create_tables':
build_table.c:324:3: warning: implicit declaration of function 'alarm' [-Wimplicit-function-declaration]
   alarm(3);
   ^
build_table.c: In function 'create_perfect_hash_table':
build_table.c:484:19: error: storage size of 'new_action' isn't known
  struct sigaction new_action, old_action;
                   ^
build_table.c:484:31: error: storage size of 'old_action' isn't known
  struct sigaction new_action, old_action;
                               ^
build_table.c:485:19: error: storage size of 'old_it' isn't known
  struct itimerval old_it;
                   ^
build_table.c:524:2: warning: implicit declaration of function 'sigemptyset' [-Wimplicit-function-declaration]
  sigemptyset(&new_action.sa_mask);
  ^
build_table.c:527:6: warning: implicit declaration of function 'sigaction' [-Wimplicit-function-declaration]
  if (sigaction(SIGALRM, NULL, &old_action) < 0) {
      ^
build_table.c:527:16: error: 'SIGALRM' undeclared (first use in this function)
  if (sigaction(SIGALRM, NULL, &old_action) < 0) {
                ^
build_table.c:537:6: warning: implicit declaration of function 'setitimer' [-Wimplicit-function-declaration]
  if (setitimer(ITIMER_REAL, NULL, &old_it) < 0){
      ^
build_table.c:537:16: error: 'ITIMER_REAL' undeclared (first use in this function)
  if (setitimer(ITIMER_REAL, NULL, &old_it) < 0){
                ^
build_table.c:485:19: warning: unused variable 'old_it' [-Wunused-variable]
  struct itimerval old_it;
                   ^
build_table.c:484:31: warning: unused variable 'old_action' [-Wunused-variable]
  struct sigaction new_action, old_action;
                               ^
build_table.c:484:19: warning: unused variable 'new_action' [-Wunused-variable]
  struct sigaction new_action, old_action;
                   ^
Makefile:1333: recipe for target 'build_table.o' failed
make[1]: *** [build_table.o] Error 1
make[1]: *** Waiting for unfinished jobs....
```

**Comment by jfoug** [comment]
Should the whole file be wrapped in a #if open_cl to turn it off?

**Comment by jfoug** [comment]
I have wrapped these in ```#if HAVE_OPENCL``` (build_table.c and hash_type_*.c) and the CircleCI build goes along happy as can be.

I have also tested a non-openCL unix and Cygwin build, and they are happy with this wrapper change.

**Comment by magnumripper** [comment]
That may be a workaround for now but we need to fix the real issue - we now can't build OpenCL on Windows at all...

**Comment by jfoug** [comment]
Of course we can. Cygwin has done this for a long time.  MinGW would also, if you installed the opencl drivers.   And it would cause these 3 files to be built and not built to empty .o files

**Comment by magnumripper** [comment]
I think you misunderstand the root issue: If you try to build OpenCL on Windows, you will again get all the warnings and errors mentioned in the original post above.

This code is only needed for OpenCL so the #if HAVE_OPENCL wrapping should be kept in there anyway - but the problems must be fixed if anyone wants to build Windows OpenCL.

**Comment by magnumripper** [comment]
And anyway, I suspect we're just missing some MinGW-specific #include or workaround for signal functions & types. A look at signals.c may give hints.

**Comment by jfoug** [comment]
Change "on Windows" to "on MinGW".  Cygwin IS on Windows.  OpenCL runs just fine.  I agree on the mingw stuff, but at this time (and I never have) had OpenCL working on MinGW. Now that I am cross compiling, I am not sure how to do it.

**Comment by magnumripper** [comment]
If that's the case I agree we can close this. I'm not sure anyone built OpenCL with MinGW yet and there will probably be other issues once someone does.
