### ISSUE TITLE
Build failure with OpenSSL 1.0.0

### ISSUE THREAD

**Issue by solardiz** [magnumripper/JohnTheRipper#2763]
Looks like we broke builds with OpenSSL 1.0.0. I think we should reintroduce support for such builds, even if with reduced functionality.

```
wpapmk.h:16:26: fatal error: openssl/cmac.h: No such file or directory
wpapsk.h:16:26: fatal error: openssl/cmac.h: No such file or directory
```

**Comment by kholia** [comment]
Thanks for fixing this @magnumripper.
