### ISSUE TITLE
office2john.py - DeprecationWarning: decodestring() is a deprecated alias since Python 3.1, use decodebytes()

### ISSUE THREAD

**Issue by A9G-Data-Droid** [magnumripper/JohnTheRipper#3345]
### WARNING ###

> office2john.py:2843: DeprecationWarning: decodestring() is a deprecated alias since Python 3.1, use decodebytes()
>   encryptedVerifierHashValue = binascii.hexlify(base64.decodestring(encryptedVerifierHashValue.encode()))
> office2john.py:2848: DeprecationWarning: decodestring() is a deprecated alias since Python 3.1, use decodebytes()
>   binascii.hexlify(base64.decodestring(saltValue.encode())).decode("ascii"),
> office2john.py:2849: DeprecationWarning: decodestring() is a deprecated alias since Python 3.1, use decodebytes()
>   binascii.hexlify(base64.decodestring(encryptedVerifierHashInput.encode())).decode("ascii"),

### Steps to reproduce ###
Run office2john.py through Python 3.7

### System configuration ###
Python 3.7 on Windows

**Comment by kholia** [comment]
We need the code to be compatible with Python 2.x (even Python 2.4 in some cases, for CentOS 6.x compatibility).

How does the new patched code behave with Python 2.x?

Can you please open a PR (pull request) for fixing this?

**Comment by A9G-Data-Droid** [comment]
@kholia It looks like office2john.py doesn't work in Python 2.4 because of an unrelated issue:

>   File "office2john.py", line 358
>     MAGIC = b'\xD0\xCF\x11\xE0\xA1\xB1\x1A\xE1'
>                                               ^
> SyntaxError: invalid syntax

**Comment by kholia** [comment]
What about Python 2.6 and 2.7?

**Comment by A9G-Data-Droid** [comment]
Ok, I have verified that my patch would break 2.6 and 2.7
both report the same error:

> AttributeError: 'module' object has no attribute 'decodebytes'

**Comment by kholia** [comment]
I am on a mobile phone now.

Check other Python code in this repository to find the `if PY3` check. That should help.
