### PR TITLE
Update INSTALL-UBUNTU

### PR DESCRIPTION
**Pull request by junquera**
zlib1g-dev is neccesary for working in Ubuntu

### CODE REVIEW

**Comment by junquera** [comment]
It could be also important to specify the libssl version (it only works with `libssl1.0-dev`, while `libssl-dev` installs a latest version in ubuntu)

**Comment by claudioandre-br** [comment]
> zlib1g-dev is neccesary for working in Ubuntu

It wasn't required (so, it is in the recommended section). Is it mandatory now? Since 18.10?

**Comment by kholia** [comment]
Yes, it is required under Debian 9 and latest Ubuntu (IIRC). I thought I updated the documentation already about this.

**Comment by junquera** [comment]
Yes, if it isn't the make process fails (at least in Ubuntu 18.10, following the guide `INSTALL-UBUNTU`). I've seen that appears as a dependency of `libssl`, it's possible that it has changed in the new repository...

Enviado desde ProtonMail móvil

**Comment by kholia** [comment]
CI says,

```
dynamic_fmt.c: In function 'FixupIfNeeded':
dynamic_fmt.c:8263:23: error: '%d' directive writing between 1 and 11 bytes into a region of size 5 [-Werror=format-overflow=]
      sprintf(Fld, "$$F%d", i);
                       ^~
dynamic_fmt.c:8263:19: note: directive argument in the range [-2147483648, 9]
      sprintf(Fld, "$$F%d", i);
                   ^~~~~~~
In file included from /usr/include/stdio.h:873,
                 from memory.h:18,
                 from common.h:21,
                 from simd-intrinsics.h:18,
                 from dynamic_fmt.c:84:
```

Did I "fix" such problems earlier? Weird.

**Comment by claudioandre-br** [comment]
As a note, it is still working for me.

```
Configured for building John the Ripper jumbo:

Target CPU ................................. x86_64 SSE2, 64-bit LE
AES-NI support ............................. depends on OpenSSL
Target OS .................................. linux-gnu
Cross compiling ............................ no
Legacy arch header ......................... x86-64.h

Optional libraries/features found:
Memory map (share/page large files) ........ yes
Fork support ............................... yes
OpenMP support ............................. yes (not for fast formats)
OpenCL support ............................. no
Generic crypt(3) format .................... yes
libgmp (PRINCE mode and faster SRP formats)  no
128-bit integer (faster PRINCE mode) ....... yes
libz (pkzip format, gpg2john) .............. no
libbz2 (gpg2john extra decompression logic)  no
libpcap (vncpcap2john and SIPdump) ......... no
librexgen (regex cracking mode) ............ no
OpenMPI support (default disabled) ......... no
ZTEX USB-FPGA module 1.15y support ......... no

Install missing libraries to get any needed features that were omitted.

Configure finished.  Now "make -s clean && make -sj4" to compile.
root@1eb2a2e6131f:/john/src# make -s clean && make -sj2
ar: creating aes.a
ar: creating ed25519-donna.a
ar: creating secp256k1.a
pkzip_fmt_plug.c:1771:2: warning: #warning pkzip format requires zlib to function. The format has been disabled [-Wcpp]
 #warning pkzip format requires zlib to function. The format has been disabled
  ^~~~~~~
stribog_fmt_plug.c:469:2: warning: #warning Stribog-256 and Stribog-512 formats require SSE 4.1, formats disabled [-Wcpp]
 #warning Stribog-256 and Stribog-512 formats require SSE 4.1, formats disabled
  ^~~~~~~

Make process completed.
```

```
# dpkg -s zlib1g-dev | grep Status
dpkg-query: package 'zlib1g-dev' is not installed and no information is available
```
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10
DISTRIB_CODENAME=cosmic
DISTRIB_DESCRIPTION="Ubuntu 18.10"
NAME="Ubuntu"
VERSION="18.10 (Cosmic Cuttlefish)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.10"
VERSION_ID="18.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic
```

**Comment by magnumripper** [comment]
> dynamic_fmt.c:8263:23: error: '%d' directive writing between 1 and 11 bytes into a region of size 5 [-Werror=format-overflow=]

Incidentally I just now got this exact error too (without this PR applied), using gcc 8.2.0 **but only with ASan**.
