### ISSUE TITLE
32bit build with GMP fails

### ISSUE THREAD

**Issue by frank-dittrich** [magnumripper/JohnTheRipper#1268]
```
$ make -s distclean ; ./configure && make -s clean && make -s 
[...]
Target CPU .................................. i686 AVX2, 32-bit LE
AES-NI support .............................. run-time detection
Target OS ................................... linux-gnu
Cross compiling ............................. no
Legacy arch header .......................... x86-sse.h

Optional libraries/features found:
Experimental code ........................... no
OpenMPI support (default disabled) .......... no
Fork support ................................ yes
OpenMP support .............................. yes
OpenCL support .............................. no
CUDA support ................................ no
Generic crypt(3) format ..................... yes
Rexgen (extra cracking mode) ................ no
GMP (PRINCE mode and faster SRP formats) .... yes
128-bit integer (faster PRINCE mode) ........ no
PCAP (vncpcap2john and SIPdump) ............. yes
BZ2 (gpg2john extra decompression logic) .... yes
Memory map (share/page large files) ......... yes

Development options (these may hurt performance when enabled):
Memdbg memory debugging settings ............ disabled
AddressSanitizer ("ASan") ................... disabled

Install missing libraries to get any needed features that were omitted.

Configure finished.  Now 'make clean && make -s' to compile.
/usr/bin/ar: creating aes.a
pp.c: In function ‘get_progress’:
pp.c:885:17: error: invalid operands to binary == (have ‘double’ and ‘struct __mpf_struct *’)
   if ((double)0 == count)
                 ^
pp.c:886:10: error: incompatible types when assigning to type ‘mpf_t’ from type ‘int’
     perc = 0;
          ^
make[1]: *** [pp.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [default] Error 2
```

**Comment by magnumripper** [comment]
Ouch, this was caused by @loverszhaokai in f86167a4.

**Comment by magnumripper** [comment]
It's a confusing issue title though. It has nothing to do with AVX2. It's about not having int128, but having GMP. Any 32-bit build with GMP will fail.

**Comment by frank-dittrich** [comment]
I didn't have time to bisect earlier, but you are right. f86167a4b4945ddf880794d27061ce01cf39d86b is the first bad commit.

**Comment by magnumripper** [comment]
I remember it because I despise reverse notations like `if (0 == foo)` even though I understand the rationale for it.

**Comment by loverszhaokai** [comment]
@frank-dittrich  

I build ok with local 32-bit laptop.

```
Configured for building John the Ripper jumbo:

Target CPU .................................. i686 SSE4.1, 32-bit LE
AES-NI support .............................. depends on OpenSSL
Target OS ................................... linux-gnu
Cross compiling ............................. no
Legacy arch header .......................... x86-sse.h

Optional libraries/features found:
Experimental code ........................... no
OpenMPI support (default disabled) .......... no
Fork support ................................ yes
OpenMP support .............................. yes
OpenCL support .............................. no
CUDA support ................................ no
Generic crypt(3) format ..................... yes
Rexgen (extra cracking mode) ................ no
GMP (PRINCE mode and faster SRP formats) .... no
128-bit integer (faster PRINCE mode) ........ no
PCAP (vncpcap2john and SIPdump) ............. no
BZ2 (gpg2john extra decompression logic) .... yes
Memory map (share/page large files) ......... yes

Development options (these may hurt performance when enabled):
Memdbg memory debugging settings ............ disabled
AddressSanitizer ("ASan") ................... disabled
```
 
**Does the super has the you environment** ?

**Comment by frank-dittrich** [comment]
Apparently you don't have libgmp installed:
```
GMP (PRINCE mode and faster SRP formats) .... no
```

Does your 32bit build without GMP have the --prince option? I guess not.

**Comment by loverszhaokai** [comment]
@frank-dittrich  

Thanks, I will have a try.
